# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='post.Post'),
        ),
    ]
