# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190722_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='delete',
            field=models.BooleanField(),
        ),
    ]
